use serde_json::Value;
use tiny_http::{Response, Server};
use anyhow::{Error, Result, anyhow};
use std::{fs, env, path::PathBuf, str::FromStr};
use ureq::{
    config::Config,
    tls::{Certificate, RootCerts, TlsConfig, TlsProvider},
};

struct Pve {
    address: String,
    username: String,
    token: String,
    node: String,
    ca_cert: Option<String>,
}

fn read_env(path: &PathBuf) -> Result<(Pve, String), Error> {
    let mut addr: Option<String> = None;
    let mut name: Option<String> = None;
    let mut token: Option<String> = None;
    let mut node: Option<String> = None;
    let mut listen_on: Option<String> = None;
    let mut ca_cert: Option<String> = None;

    let content = fs::read_to_string(path)
        .map_err(|e| anyhow!("failed to open config file {}: {}", path.display(), e))?;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            match key.trim() {
                "pve"       => addr = Some(value.trim().to_string()),
                "name"      => name = Some(value.trim().to_string()),
                "token"     => token = Some(value.trim().to_string()),
                "node"      => node = Some(value.trim().to_string()),
                "listen-on" => listen_on = Some(value.trim().to_string()),
                "ca-cert"   => ca_cert = Some(value.trim().to_string()),
                _ => (),
            }
        }
    }
    let info = Pve {
        address: addr.unwrap(),
        username: name.unwrap(),
        token: token.unwrap(),
        node: node.unwrap(),
        ca_cert,
    };
    Ok((info, listen_on.unwrap()))
}

fn assemble_vv(data: &Value, pve: &Pve) -> String {
    let temp = pve.address.clone();
    let ip = temp.as_str().rsplit(":").last().unwrap();
    let port = data["proxy"].as_str().unwrap().split(":").last().unwrap();
    let construct_address = format!("{}:{}", ip, port);

    format!(
        "# this file was generated by pve-spice-puller
            [virt-viewer]
            secure-attention={}
            tls-port={}
            title={}
            toggle-fullscreen={}
            type={}
            password={}
            proxy=http://{}
            ca={}
            host={}
            release-cursor={}
            delete-this-file=1
            host-subject={}",
        data["secure-attention"].as_str().unwrap(),
        data["tls-port"].as_i64().unwrap(),
        data["title"].as_str().unwrap(),
        data["toggle-fullscreen"].as_str().unwrap(),
        data["type"].as_str().unwrap(),
        data["password"].as_str().unwrap(),
        construct_address.as_str(),
        data["ca"].as_str().unwrap(),
        data["host"].as_str().unwrap(),
        data["release-cursor"].as_str().unwrap(),
        data["host-subject"].as_str().unwrap(),
    )
}

fn build_tls_config(pve: &Pve, no_cert: bool) -> Result<TlsConfig, Error> {
    if no_cert {
        eprintln!("[warning] pve-spice-puller runs in insecure mode, \
            because it was enabled by --no-cert flag");
        return Ok(TlsConfig::builder()
            .provider(TlsProvider::Rustls)
            .disable_verification(true)
            .build());
    }

    let mut certs = Vec::new();

    let native_certs = rustls_native_certs::load_native_certs()
        .map_err(|e| anyhow!("failed to load system certs: {}", e))?;
    for cert in native_certs {
        certs.push(Certificate::from_der(cert.as_ref()).to_owned());
    }

    if let Some(ca_path) = &pve.ca_cert {
        let pem = fs::read(ca_path)
            .map_err(|e| anyhow!("failed to read CA cert at {}: {}", ca_path, e))?;
        let custom_cert = Certificate::from_pem(&pem)
            .map_err(|e| anyhow!("failed to parse CA cert at {}: {}", ca_path, e))?;
        certs.push(custom_cert);
        println!("using custom CA: {}", ca_path);
    } else {
        println!("using system CA certificates");
    }

    Ok(TlsConfig::builder()
        .provider(TlsProvider::Rustls)
        .root_certs(RootCerts::new_with_certs(&certs))
        .build())
}

fn get_vv(pve: &Pve, vm: u8, no_cert: bool) -> Response<std::io::Cursor<Vec<u8>>> {
    let tls_config = match build_tls_config(pve, no_cert) {
        Ok(c) => c,
        Err(e) => {
            return Response::from_string(format!("tls config error: {}", e))
                .with_status_code(500);
        }
    };

    let config = Config::builder()
        .tls_config(tls_config)
        .build();

    let api = format!(
        "https://{}/api2/json/nodes/{}/qemu/{}/spiceproxy",
        pve.address, pve.node, vm
    );

    let agent = config.new_agent();
    let res = agent
        .post(api)
        .header("Authorization", &format!("PVEAPIToken={}={}", pve.username, pve.token))
        .send_empty();

    let res = match res {
        Ok(r) => r,
        Err(e) => {
            return Response::from_string(format!("smth gone wrong on pve side: {}", e))
                .with_status_code(500);
        }
    };

    let body = res.into_body().read_to_string().unwrap();
    let json: Value = serde_json::from_str(&body).unwrap_or_else(|_| Value::Null);

    if json["data"].is_null() {
        return Response::from_string("pve responded with nothing").with_status_code(500);
    }

    let data = &json["data"];
    let header2 = format!("Content-Disposition: attachment; filename=\"console_{}.vv\"", vm);

    Response::from_string(assemble_vv(data, pve))
        .with_header(tiny_http::Header::from_str("Content-Type: application/x-virt-viewer").unwrap())
        .with_header(tiny_http::Header::from_str(&header2).unwrap())
        .with_status_code(200)
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let mut no_cert = false;
    let mut config_path: Option<PathBuf> = None;

    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--no-cert" => no_cert = true,
            "--config" => {
                i += 1;
                config_path = Some(PathBuf::from(
                    args.get(i).expect("--config requires a path argument"),
                ));
            }
            _ => {}
        }
        i += 1;
    }

    let env_path = match config_path {
        Some(p) => p,
        None => {
            let mut p = env::current_exe().expect("something wrong with the exe path");
            if p.to_string_lossy().contains("target") {
                p.pop();
                p.pop();
            }
            p.pop();
            p.push(".config");
            p
        }
    };

    let (the_pve, listen_addr) = match read_env(&env_path) {
        Ok((pve, listen_on)) => {
            println!("conf load ok");
            (pve, listen_on)
        }
        Err(e) => {
            panic!("conf load not ok: {}", e);
        }
    };

    let server = Server::http(&listen_addr).expect("failed to run server");
    println!("listening on {}/get_config/*vm_id*", &listen_addr);

    for request in server.incoming_requests() {
        if request.url().starts_with("/get_config") && request.method() == &tiny_http::Method::Get {
            let id = request.url().split("/").last().expect("vm number is incorrect");
            println!("serving a request from {}, providing config to {}",
                request.remote_addr().unwrap(), &id);
            let vm: u8 = id.parse::<u8>().expect("cant parse the vm number");
            let response = get_vv(&the_pve, vm, no_cert);
            request.respond(response).unwrap();
        }
    }
}